spring:
  application:
    name: gateway-service    
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/    
    service:
      name: gateway-service
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      elasticsearch:
        hosts: localhost:9200            
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin      

eureka:  
  client:
    region: default
    registryFetchIntervalSeconds: 20  
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8082/discovery-service/eureka/

zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 300000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 300000
  routes:      
    discovery-service:
      path: /discovery-service/**
      sensitive-headers: 
      url: http://localhost:8082/discovery-service
    book-service:
      path: /book-service/**
      sensitive-headers: 
      url: http://localhost:8083/book-service
    user-service:
      path: /user-service/**
      sensitive-headers: 
      url: http://localhost:8084/user-service

ribbon:
  ReadTimeout: 300000
  connection-timeout: 300000
  eureka:
    enabled: true

hystrix:
  shareSecurityContext: true 
  command:
    discovery-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    book-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

springdoc:
  api-docs:
    enabled: true    
  swagger-ui:    
    urls:      
      - name: book-service
        url: /book-service/api-docs
      - name: user-service
        url: /user-service/api-docs

server:
  port: 8080
  forward-headers-strategy: framework  
  servlet:
    context-path:
